### PR TITLE
this commit add solution to task 11 delete comment

### PR DESCRIPTION
**Pull request by Topecoding206**

### CODE REVIEW

**Review by yalicee — CHANGES_REQUESTED** [review]
Your delete functionality is not working because you are optimistically rendering your comment before it is posted so when I delete it, it doesnt have an id yet.

**Comment by Topecoding206** [comment]
Thanks Alice i will get it done and send another pr tomorrow

**Review by emilyb93 — CHANGES_REQUESTED** [review]
Change this code to only be updating on the response and this is good to go :)

**Review by yalicee — APPROVED** [review]
Looks great now thank you :)

**Comment by Topecoding206** [comment]
Great

**Pull request merged**
